# Generated by Django 2.0 on 2018-02-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='comlete',
            new_name='complete',
        ),
    ]
